module.exports.ResponseMessage = {
  SUCCESS: "success",
  FAILURE: "failure",
  USER_NOT_FOUND: "User not found",
  INVALID_CREDENTIALS: "Invalid credentials",
  INTERNAL_SERVER_ERROR: "Internal server error",
  UNAUTHORIZED: "Unauthorized",
  ALL_FIELDS_ARE_REQUIRED: "All fields are required",
  INVALID_PASSWORD: "Invalid password",
  TOKEN_IS_MISSING: "Token is missing",
  AUTHORIZATION_TOKEN_IS_MISSING: "Authorization token is missing",
  AUTHORIZATION_TOKEN_IS_INVALID: "Authorization token is invalid",
  PRODUCT_CREATED_SUCCESSFULLY: "Product created successfully",
  PRODUCT_NOT_FOUND: "Product not found",
};
